export const pubKeyStrings = [
  `
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    mDMEZyOaoRYJKwYBBAHaRw8BAQdA99Fz0gIxMw3W12/wnm8ksTBwG/fiahcv2ux5
    6QHvzBq0IURhdmlkIEV4YW1wbGUgPGRhdmlkQGV4YW1wbGUuY29tPoiZBBMWCgBB
    FiEEYxG14itq5TLQKVi+8gd1p5hd1scFAmcjmqECGwMFCQWjmoAFCwkIBwICIgIG
    FQoJCAsCBBYCAwECHgcCF4AACgkQ8gd1p5hd1sd6wwEArvOhqSSD65eTA4HXWO6D
    PEQMrezrE3wroE4h/5smd00A/0aDinxdJzQvJRMKi1/R2Bi4iXKFVJF6xToyois7
    HyIMuDgEZyOaoRIKKwYBBAGXVQEFAQEHQHSB/l1bjBRc++CNvXUOjgT9BCC85JZD
    M6nUOrHcdwwtAwEIB4h+BBgWCgAmFiEEYxG14itq5TLQKVi+8gd1p5hd1scFAmcj
    mqECGwwFCQWjmoAACgkQ8gd1p5hd1sdK+gD9Eoy8HHSMu1xLfcsqigxR6Sy5QGcL
    6NfI5ZvhK6+YBjkBAPLkSrlMbu0SqtAEJV6pru3CV+kFFsM/vbKBAvBh2KAG
    =CyvR
    -----END PGP PUBLIC KEY BLOCK-----
  `,
];
